### PR TITLE
Fixed idle timeout dialog design

### PR DESCRIPTION
**Pull request by vkallerud**
... and extended inactivityTime (time till idle timout is triggered).

### CODE REVIEW

**Comment by jmehmandarova** [comment]
Can I make a pitch for 20 sec.? Or do people think that's too short?

**Comment by ComputasAlex** [comment]
The dialog autofocuses on "Avslutt nå". On purpose?

Skjermbilde 2024-07-17 kl  10 00 23

**Review by ComputasAlex — APPROVED** [review]
I think is good

**Comment by vkallerud** [comment]
> The dialog autofocuses on "Avslutt nå". On purpose?
> 
> Skjermbilde 2024-07-17 kl 10 00 23

Yeah its kind of wack. On some pages the styling is a bit too general, and overrides the styling on the idle timeout component (which uses IDs and targets each element in the component very specifically). As we are going to implement new button designs and do some general SCSS cleanup towards the end of the sprint, it makes sense to re-adress this issue then (as it might be solved implicitly during the cleanup).

**Comment by vkallerud** [comment]
> Can I make a pitch for 20 sec.? Or do people think that's too short?

I set it to 25 seconds. Should observe whether this is sufficiently long/short during next visit to TM.

**Pull request merged**
